config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to @task
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.0.10/css/all.css'></link>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.check_box :completed %>

  <%= t.submit  value = "Create New Task" %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul><% @tasks.each do |task| %>
  <li> <input type="checkbox" <%= "checked" if task.completed %>><%= link_to task.title, task_path(task) %>
  <%= link_to raw("<i class='far fa-trash-alt'></i>"), task_path(task),  method: :delete,
   data: { confirm: 'Are you sure?' }%>
  </li>
  <% end %>
</ul>

<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>

<p><%= link_to "Edit Task", edit_path(@task) %></p>

<p><%= link_to "Back to List", tasks_path %></p>

<p><%= link_to "Delete", tasks_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>